repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: ['--maxkb=500']
    -   id: debug-statements
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        language_version: python3.9

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-bugbear==23.7.10]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        types: [python]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
    -   id: mypy
        additional_dependencies: [django-stubs==4.2.0]
        args: [--ignore-missing-imports, --disallow-untyped-defs]
        exclude: ^(migrations|tests/|setup\.py$)

-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
    -   id: mdformat
        additional_dependencies: [mdformat-gfm, mdformat-toc]
        types: [markdown]

-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
    -   id: markdownlint
        args: [--fix, --ignore-path', '.gitignore']
        types: [markdown]

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.5.2
    hooks:
    -   id: commitizen
        stages: [commit-msg]
        additional_dependencies: [commitizen==3.5.2]
