version: '3.8'

services:
  web:
    command: bash -c "python manage.py wait_for_db && python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1
      - DJANGO_DEBUG=True
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - venv:/app/venv
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true

volumes:
  venv:
