# Generated by Django 5.2.1 on 2025-05-27 07:17

from django.db import migrations, models
import django.db.models.deletion


def migrate_old_to_new_fields(apps, schema_editor):
    """Migrate data from old fields to new i18n fields."""
    ColoringPage = apps.get_model('coloring_pages', 'ColoringPage')
    for page in ColoringPage.objects.all():
        # If the new fields are empty but old fields have data, copy them
        if not hasattr(page, 'title_en') and hasattr(page, 'title'):
            page.title_en = page.title
            page.title_de = page.title  # Use English as fallback for German
            page.description_en = getattr(page, 'description', '')
            page.description_de = getattr(page, 'description', '')
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('coloring_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloringpage',
            name='description_de',
            field=models.TextField(default='', verbose_name='Description (German)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coloringpage',
            name='description_en',
            field=models.TextField(default='', verbose_name='Description (English)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coloringpage',
            name='title_de',
            field=models.CharField(default='', max_length=200, verbose_name='Title (German)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coloringpage',
            name='title_en',
            field=models.CharField(default='', max_length=200, verbose_name='Title (English)'),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=migrate_old_to_new_fields,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='coloringpage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='coloringpage',
            name='title',
        ),
    ]
