# Generated by Django 4.2.21 on 2025-05-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring_pages', '0002_add_i18n_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloringpage',
            name='seo_url_de',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='SEO URL (German)'),
        ),
        migrations.AddField(
            model_name='coloringpage',
            name='seo_url_en',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='SEO URL (English)'),
        ),
    ]
