# Generated by Django 4.2.21 on 2025-05-27 21:26

from django.db import migrations
from django.utils.text import slugify

def create_unique_slug(model, field_value, slug_field_name):
    """
    Create a unique slug by appending an index if necessary.
    """
    slug = slugify(field_value)
    unique_slug = slug
    num = 1
    
    # Check if a slug with this name already exists
    while model.objects.filter(**{f"{slug_field_name}__iexact": unique_slug}).exists():
        unique_slug = f"{slug}-{num}"
        num += 1
    
    return unique_slug
def add_seo_urls(apps, schema_editor):
    """
    Generate SEO URLs for existing coloring pages.
    """
    ColoringPage = apps.get_model('coloring_pages', 'ColoringPage')
    
    for page in ColoringPage.objects.all():
        if not page.seo_url_en and page.title_en:
            page.seo_url_en = create_unique_slug(ColoringPage, page.title_en, 'seo_url_en')
        if not page.seo_url_de and page.title_de:
            page.seo_url_de = create_unique_slug(ColoringPage, page.title_de, 'seo_url_de')
        page.save(update_fields=['seo_url_en', 'seo_url_de'])

class Migration(migrations.Migration):

    dependencies = [
        ('coloring_pages', '0003_add_seo_url_fields'),
    ]

    operations = [
        migrations.RunPython(add_seo_urls, migrations.RunPython.noop),
    ]
