# Generated by Django 4.2.21 on 2025-06-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring_pages', '0004_add_seo_urls_to_existing_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=255)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('referrer', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query', 'created_at'], name='coloring_pa_query_1ad22b_idx'), models.Index(fields=['session_key', 'created_at'], name='coloring_pa_session_19cfde_idx'), models.Index(fields=['ip_address', 'created_at'], name='coloring_pa_ip_addr_c24f41_idx')],
            },
        ),
    ]
