# Generated by Django 4.2.21 on 2025-06-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring_pages', '0005_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='referrer_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='user_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
