# Generated by Django 4.2.21 on 2025-06-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring_pages', '0006_searchquery_referrer_url_searchquery_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_provider', models.CharField(help_text='The provider of the AI model (e.g., OpenAI, Anthropic, etc.)', max_length=100, verbose_name='Model Provider')),
                ('model_name', models.CharField(help_text='The name of the specific model (e.g., gpt-4, claude-2, etc.)', max_length=100, verbose_name='Model Name')),
                ('prompt', models.TextField(help_text='The system prompt to use with this model', verbose_name='System Prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'System Prompt',
                'verbose_name_plural': 'System Prompts',
                'ordering': ['model_provider', 'model_name'],
                'unique_together': {('model_provider', 'model_name')},
            },
        ),
    ]
