# Generated by Django 4.2.21 on 2025-06-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring_pages', '0007_systemprompt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemprompt',
            options={'ordering': ['name', 'model_provider', 'model_name'], 'verbose_name': 'System Prompt', 'verbose_name_plural': 'System Prompts'},
        ),
        migrations.AddField(
            model_name='systemprompt',
            name='name',
            field=models.CharField(default='Unnamed Prompt', help_text='A descriptive name for this system prompt', max_length=200, verbose_name='Name'),
        ),
    ]
