# Generated by Django 4.2.21 on 2025-06-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring_pages', '0008_alter_systemprompt_options_systemprompt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coloringpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='coloringpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='searchquery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddIndex(
            model_name='coloringpage',
            index=models.Index(fields=['seo_url_en'], name='coloring_pa_seo_url_05e1d6_idx'),
        ),
        migrations.AddIndex(
            model_name='coloringpage',
            index=models.Index(fields=['seo_url_de'], name='coloring_pa_seo_url_d9bdad_idx'),
        ),
    ]
