# Generated by Django 4.2.21 on 2025-06-03 11:15

from django.db import migrations


def create_default_image_prompt(apps, schema_editor):
    SystemPrompt = apps.get_model('coloring_pages', 'SystemPrompt')
    
    # Create the default image prompt if it doesn't exist
    SystemPrompt.objects.get_or_create(
        name='default-image',
        defaults={
            'model_provider': 'OpenAI',
            'model_name': 'gpt-image-1',
            'prompt': (
                "Create a clean black and white line drawing of %(prompt)s. "
                "Use smooth, continuous black lines on pure white background. "
                "No color, shading, gradients, textures, or patterns. "
                "No background elements, borders, frames, shadows, or drop shadows. "
                "No text, labels, or additional objects. Focus only on the main subject. "
                "The image should be a single, clear outline drawing with all lines connected. "
                "The subject should be centered and fill most of the frame WITHOUT TOUCHING THE EDGES. "
                "Avoid cutting off the main subject. "
                "Do not include any elements that suggest it's a coloring page unless those are explicitly "
                "part of the prompt (NO PENCILS, CRAYONS, ETC.). "
                "If you are asked for example for 'a cat' this means 'one cat' not multiple cats. "
                "Avoid duplication of objects if not asked for. "
                "If the object is likely to have a highly detailed pattern, such as a flower or a leaf or the fur "
                "of a pet, do not include it so it can be colored."
            )
        }
    )


def remove_default_image_prompt(apps, schema_editor):
    SystemPrompt = apps.get_model('coloring_pages', 'SystemPrompt')
    SystemPrompt.objects.filter(name='default-image').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('coloring_pages', '0009_alter_coloringpage_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_image_prompt, remove_default_image_prompt),
    ]
