# Generated by Django 4.2.21 on 2025-06-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring_pages', '0010_add_default_image_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='coloringpage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata stored as JSON', null=True),
        ),
    ]
