# Generated by Django 4.2.21 on 2025-06-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring_pages', '0011_coloringpage_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemprompt',
            name='quality',
            field=models.CharField(choices=[('standard', 'Standard'), ('hd', 'HD')], default='standard', help_text='Image generation quality setting', max_length=10, verbose_name='Quality'),
        ),
    ]
