# Generated by Django 4.2.21 on 2025-06-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring_pages', '0013_update_system_prompt_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprompt',
            name='quality',
            field=models.CharField(default='standard', help_text='Image generation quality setting (e.g., standard, hd)', max_length=20, verbose_name='Quality'),
        ),
    ]
