# Generated by Django 4.2.22 on 2025-06-08 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coloring_pages', '0015_update_default_prompt_quality'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systemprompt',
            unique_together=set(),
        ),
    ]
